let
    Source = Excel.Workbook(File.Contents("C:\Users\marce\OneDrive\Documents\Dissertation\Data\Data Collection.xlsm"), null, true),
    #"Data - Base_Sheet" = Source{[Item="Data - Base",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Data - Base_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Helper", type text}, {"ID", type text}, {"Forename(s)", type text}, {"Surname", type text}, {"Date of Birth", type date}, {"Age Group", type text}, {"Position", type text}, {"Attribute1", type text}, {"W Cup Scoop", type any}, {"Comment", type any}, {"Parrying shots", type any}, {"Comment_1", type any}, {"Diving techniques", type any}, {"Comment_2", type any}, {"Passing / Ball Striking", type any}, {"Comment_3", type any}, {"Passing into defence or midfield or strikers", type any}, {"Comment_4", type any}, {"Quality first touch to set the next action off both feet.", type any}, {"Comment_5", type any}, {"Blocking and spreading shapes", type any}, {"Comment_6", type any}, {"Smothering shapes", type any}, {"Comment_7", type any}, {"Able to catch high balls consistently.", type any}, {"Comment_8", type any}, {"Refine scoop, cup, W, collapse save.", Int64.Type}, {"Comment_9", Int64.Type}, {"Ball manipulation", type any}, {"Comment_10", type any}, {"Ball striking", type any}, {"Comment_11", type any}, {"Receiving skills", type any}, {"Comment_12", type any}, {"Receiving", type any}, {"Comment_13", type any}, {"Fakes and feints", type any}, {"Comment_14", type any}, {"Receiving to play forwards", type any}, {"Comment_15", type any}, {"Passing into defence or midfield or strikers_16", type any}, {"Comment_17", type any}, {"Quality first touch to set the next action off both feet._18", type any}, {"Comment_19", type any}, {"Blocking and spreading shapes_20", type any}, {"Comment_21", type any}, {"Smothering shapes_22", type any}, {"Comment_23", type any}, {"Able to catch high balls consistently._24", type any}, {"Comment_25", type any}, {"Passing (long and short)", type any}, {"Comment_26", type any}, {"Heading", type any}, {"Comment_27", type any}, {"Ball striking and passing techniques off both feet over all types of distance", Int64.Type}, {"Comment_28", Int64.Type}, {"Receiving skills off both feet to allow two touch play", Int64.Type}, {"Comment_29", Int64.Type}, {"Scanning techniques to see the next pass", Int64.Type}, {"Comment_30", Int64.Type}, {"Refine high ball catching techniques", Int64.Type}, {"Comment_31", Int64.Type}, {"Refine diving techniques", Int64.Type}, {"Comment_32", Int64.Type}, {"Receiving to come inside or go on the outside", Int64.Type}, {"Comment_33", Int64.Type}, {"Ball striking e.g. shooting or long passing", Int64.Type}, {"Comment_34", Int64.Type}, {"Set piece specialist", Int64.Type}, {"Comment_35", Int64.Type}, {"Receiving on both feet to play forwards or switch", Int64.Type}, {"Comment_36", Int64.Type}, {"Running with the ball", Int64.Type}, {"Comment_37", Int64.Type}, {"Defending 1v1", Int64.Type}, {"Comment_38", Int64.Type}, {"Fakes and feints to step pass the first line of pressure", Int64.Type}, {"Comment_39", Int64.Type}, {"Heading off long balls and heading to defend crosses", Int64.Type}, {"Comment_40", Int64.Type}, {"Know when to step across your opponent to win the ball", Int64.Type}, {"Comment_41", Int64.Type}, {"Attacking 1v1", Int64.Type}, {"Comment_42", Int64.Type}, {"Crossing - all varieties", Int64.Type}, {"Comment_43", Int64.Type}, {"Shooting / Finishing", Int64.Type}, {"Comment_44", Int64.Type}, {"Passing (long and short) off both feet", Int64.Type}, {"Comment_45", Int64.Type}, {"Creative passing with disguise", Int64.Type}, {"Comment_46", Int64.Type}, {"Twisting and turning", Int64.Type}, {"Comment_47", Int64.Type}, {"One touch play to combine", Int64.Type}, {"Comment_48", Int64.Type}, {"Multi-directional receiving skills on all surfaces", Int64.Type}, {"Comment_49", Int64.Type}, {"Passing", Int64.Type}, {"Comment_50", Int64.Type}, {"One touch finishing skills", Int64.Type}, {"Comment_51", Int64.Type}, {"Attribute2", type text}, {"Dealing with 1v1's", type any}, {"Comment_52", type any}, {"Distribution techniques (feet or space)", type any}, {"Comment_53", type any}, {"Stretching play or coming short", type any}, {"Comment_54", type any}, {"Noticing where there is space and spreading out", type any}, {"Comment_55", type any}, {"How to position to make the pitch smaller", type any}, {"Comment_56", type any}, {"How to mark an opponent", type any}, {"Comment_57", type any}, {"When to come out and effect crosses", type any}, {"Comment_58", type any}, {"Shot stopping", type any}, {"Comment_59", type any}, {"Defending the space to prevent 1v1's", type any}, {"Comment_60", type any}, {"Distribution techniques (playing into or onto).", type any}, {"Comment_61", type any}, {"Organising markers on corners, walls on free kicks etc", type any}, {"Comment_62", type any}, {"Positioning to play out from the back", type any}, {"Comment_63", type any}, {"How to bring an opponent towards you to play round them.", type any}, {"Comment_64", type any}, {"How to read an opponents body shape to spot triggers", type any}, {"Comment_65", type any}, {"How to create a 2v1 overload on an opponent", type any}, {"Comment_66", type any}, {"Where to position to receive", type any}, {"Comment_67", type any}, {"Defending in balance principles", type any}, {"Comment_68", type any}, {"Defending out of balance principles", type any}, {"Comment_69", type any}, {"When to run forward and when to hold your position", type any}, {"Comment_70", type any}, {"When to combine and when to dribble", type any}, {"Comment_71", type any}, {"Forward runs to penetrate", type any}, {"Comment_72", type any}, {"How to press the opposition back line", type any}, {"Comment_73", type any}, {"Noticing where overloads are to help the team build from the back line.", type any}, {"Comment_74", type any}, {"Take up suitable start positions to help sweep up long balls played behind the backline", type any}, {"Comment_75", type any}, {"How to deal with and organise walls and marking positions for defending set pieces", type any}, {"Comment_76", type any}, {"Know when to ask for more pressure on the ball or when a clearance needs to be made", type any}, {"Comment_77", type any}, {"Notice how high the opposition are pressing to influence your own distribution.", type any}, {"Comment_78", type any}, {"Dealing with crosses", type any}, {"Comment_79", type any}, {"Explore different pressing strategies", type any}, {"Comment_80", type any}, {"How to rotate effectively with your wide player to create space", type any}, {"Comment_81", type any}, {"Explore defending in a back three and a back four ", type any}, {"Comment_82", type any}, {"How to defend against one striker or two strikers", type any}, {"Comment_83", type any}, {"How to position to help build play from the back", type any}, {"Comment_84", type any}, {"How to deal with being pressed from the inside or outside", type any}, {"Comment_85", type any}, {"How to defend when there is no pressure on the ball", type any}, {"Comment_86", type any}, {"Recognise where to set the defensive line to play offside", type any}, {"Comment_87", type any}, {"When to stay wide and when to come inside as a wide midfielder", type any}, {"Comment_88", type any}, {"How to play as single pivot in midfield or as a double pivot", type any}, {"Comment_89", type any}, {"How to play in a midfield two, a midfield three or midfield four", type any}, {"Comment_90", type any}, {"How to position to get on the ball from the defenders", type any}, {"Comment_91", type any}, {"How to play against a midfield two, a midfield three or midfield four", type any}, {"Comment_92", type any}, {"When to stay wide and when to come inside as a wide forward", type any}, {"Comment_93", type any}, {"When to pass and when to dribble", type any}, {"Comment_94", type any}, {"How to rotate effectively with your full back to create space", type any}, {"Comment_95", type any}, {"Recognise what type of cross needs to be delivered", type any}, {"Comment_96", type any}, {"Know when to make movements to come short or when to go in behind", type any}, {"Comment_97", type any}, {"How to position to anticipate second balls", type any}, {"Comment_98", type any}, {"How to play as a lone centre forward and how to play as a front two", type any}, {"Comment_99", type any}, {"When to come short and when to make a penetrating run", type any}, {"Comment_100", type any}, {"How to high press against a back four or back three", type any}, {"Comment_101", type any}, {"Movement to create space to support build up play", type any}, {"Comment_102", type any}, {"Movement to create space inside the penalty box.", type any}, {"Comment_103", type any}, {"Knows when to play feet or space.", Int64.Type}, {"Comment_104", Int64.Type}, {"Recognises what type of pass to play depending on opposition shape", Int64.Type}, {"Comment_105", Int64.Type}, {"Takes up suitable positions to defend the cross", Int64.Type}, {"Comment_106", Int64.Type}, {"Makes suitable decisions to deal with the cross (catch or punch).", Int64.Type}, {"Comment_107", Int64.Type}, {"Knows how and where to set in relation to the shot.", Int64.Type}, {"Comment_108", Int64.Type}, {"Recognises when to use different techniques to defend the goal.", Int64.Type}, {"Comment_109", Int64.Type}, {"Influences defenders to deny goal scoring opportunties.", Int64.Type}, {"Comment_110", Int64.Type}, {"Support positions towards or away from the ball", Int64.Type}, {"Comment_111", Int64.Type}, {"How to position to help build play from the back and outplay different pressing strategies", Int64.Type}, {"Comment_112", Int64.Type}, {"How to press the game in different ways as a full back in different formations", Int64.Type}, {"Comment_113", Int64.Type}, {"When to position on the inside or outside and high or low in the pitch to support the ball", Int64.Type}, {"Comment_114", Int64.Type}, {"How to effectively position to lock play down in the opposition half", Int64.Type}, {"Comment_115", Int64.Type}, {"How to defend the back post effectively on crosses.", Int64.Type}, {"Comment_116", Int64.Type}, {"How to defend when overloaded in wide areas", Int64.Type}, {"Comment_117", Int64.Type}, {"How to effectively support your wide player and overload the opposition full back", Int64.Type}, {"Comment_118", Int64.Type}, {"How to defend in a mid-block or deep block", Int64.Type}, {"Comment_119", Int64.Type}, {"Understand the positional requirements of playing in a back three and a back four.", Int64.Type}, {"Comment_120", Int64.Type}, {"How to mark effectively against one strike or two strikers", Int64.Type}, {"Comment_121", Int64.Type}, {"How to position to help build play from the back to manipulate the oppositions pressing strategy", Int64.Type}, {"Comment_122", Int64.Type}, {"Know how to deal with opposition midfielders playing in the pocket. ", Int64.Type}, {"Comment_123", Int64.Type}, {"Know when to play short and when to play long from the back.", Int64.Type}, {"Comment_124", Int64.Type}, {"Know how to position effectively when there is no pressure on the ball.", Int64.Type}, {"Comment_125", Int64.Type}, {"Organise the defensive line to play offside.", Int64.Type}, {"Comment_126", Int64.Type}, {"Know when to run into space or when to support a pass and receive to feet.", Int64.Type}, {"Comment_127", Int64.Type}, {"Know when to stay wide and when to come inside as a wide midfielder", Int64.Type}, {"Comment_128", Int64.Type}, {"Know how to rotate with full backs and central midfielders to create space", Int64.Type}, {"Comment_129", Int64.Type}, {"Know when to come inside or go outside when you have the ball at your feet.", Int64.Type}, {"Comment_130", Int64.Type}, {"Know how to lose your opponent with quick and late movements", Int64.Type}, {"Comment_131", Int64.Type}, {"Know which cross needs to be delivered depending on your position", Int64.Type}, {"Comment_132", Int64.Type}, {"Know when to position on the outside to receive the ball.", Int64.Type}, {"Comment_133", Int64.Type}, {"Know the midfield roles of a single pivot, double pivot or number 8 in midfield.", Int64.Type}, {"Comment_134", Int64.Type}, {"Know when to hold your position or run forwards as a central midfielder", Int64.Type}, {"Comment_135", Int64.Type}, {"Know how to pin an opponent as a central midfielder", Int64.Type}, {"Comment_136", Int64.Type}, {"How to defend effectively in midfield (when to press, when to drop, when to cover).", Int64.Type}, {"Comment_137", Int64.Type}, {"Know how to defend as a midfield three or four.", Int64.Type}, {"Comment_138", Int64.Type}, {"Know how to rotate with other central midfielders to create space to receive.", Int64.Type}, {"Comment_139", Int64.Type}, {"Know how to make blind side runs in behind the back line", Int64.Type}, {"Comment_140", Int64.Type}, {"Know how to create seperation between you and your opponent when making a run in behind", Int64.Type}, {"Comment_141", Int64.Type}, {"Know how to press the game as a striker", Int64.Type}, {"Comment_142", Int64.Type}, {"Know how to play in a mid-block or low block and screen midfielders as a striker", Int64.Type}, {"Comment_143", Int64.Type}, {"Know how to make double movements in and out the penalty box to create space", Int64.Type}, {"Comment_144", Int64.Type}, {"Know when to make runs across your opponent inside the penalty box.", Int64.Type}, {"Comment_145", Int64.Type}, {"Know how to pin your defender to receive the ball to feet", Int64.Type}, {"Comment_146", Int64.Type}, {"Know how to win free kicks off your opponent", Int64.Type}, {"Comment_147", Int64.Type}, {"Attribute3", type text}, {"Speed", Int64.Type}, {"Comment_148", Int64.Type}, {"Mobility", Int64.Type}, {"Comment_149", Int64.Type}, {"Agility", Int64.Type}, {"Comment_150", Int64.Type}, {"Acceleration", Int64.Type}, {"Comment_151", Int64.Type}, {"Power", Int64.Type}, {"Comment_152", Int64.Type}, {"Strength", Int64.Type}, {"Comment_153", Int64.Type}, {"Attribute4", type text}, {"Confidence", Int64.Type}, {"Comment_154", Int64.Type}, {"Decision Making", Int64.Type}, {"Comment_155", Int64.Type}, {"Communication", Int64.Type}, {"Comment_156", Int64.Type}, {"Focus", Int64.Type}, {"Comment_157", Int64.Type}, {"Leadership", Int64.Type}, {"Comment_158", Int64.Type}, {"Resilience", Int64.Type}, {"Comment_159", Int64.Type}}),
    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
    #"Removed Other Columns" = Table.SelectColumns(#"Removed Top Rows",{"Helper", "ID", "Forename(s)", "Surname", "Date of Birth", "Age Group", "Position", "Attribute1", "W Cup Scoop", "Parrying shots", "Diving techniques", "Passing / Ball Striking", "Passing into defence or midfield or strikers", "Quality first touch to set the next action off both feet.", "Blocking and spreading shapes", "Smothering shapes", "Able to catch high balls consistently.", "Refine scoop, cup, W, collapse save.", "Ball manipulation", "Ball striking", "Receiving skills", "Receiving", "Fakes and feints", "Receiving to play forwards", "Passing into defence or midfield or strikers_16", "Quality first touch to set the next action off both feet._18", "Blocking and spreading shapes_20", "Smothering shapes_22", "Able to catch high balls consistently._24", "Passing (long and short)", "Heading", "Ball striking and passing techniques off both feet over all types of distance", "Receiving skills off both feet to allow two touch play", "Scanning techniques to see the next pass", "Refine high ball catching techniques", "Refine diving techniques", "Receiving to come inside or go on the outside", "Ball striking e.g. shooting or long passing", "Set piece specialist", "Receiving on both feet to play forwards or switch", "Running with the ball", "Defending 1v1", "Fakes and feints to step pass the first line of pressure", "Heading off long balls and heading to defend crosses", "Know when to step across your opponent to win the ball", "Attacking 1v1", "Crossing - all varieties", "Shooting / Finishing", "Passing (long and short) off both feet", "Creative passing with disguise", "Twisting and turning", "One touch play to combine", "Multi-directional receiving skills on all surfaces", "Passing", "One touch finishing skills", "Attribute2", "Dealing with 1v1's", "Distribution techniques (feet or space)", "Stretching play or coming short", "Noticing where there is space and spreading out", "How to position to make the pitch smaller", "How to mark an opponent", "When to come out and effect crosses", "Shot stopping", "Defending the space to prevent 1v1's", "Distribution techniques (playing into or onto).", "Organising markers on corners, walls on free kicks etc", "Positioning to play out from the back", "How to bring an opponent towards you to play round them.", "How to read an opponents body shape to spot triggers", "How to create a 2v1 overload on an opponent", "Where to position to receive", "Defending in balance principles", "Defending out of balance principles", "When to run forward and when to hold your position", "When to combine and when to dribble", "Forward runs to penetrate", "How to press the opposition back line", "Noticing where overloads are to help the team build from the back line.", "Take up suitable start positions to help sweep up long balls played behind the backline", "How to deal with and organise walls and marking positions for defending set pieces", "Know when to ask for more pressure on the ball or when a clearance needs to be made", "Notice how high the opposition are pressing to influence your own distribution.", "Dealing with crosses", "Explore different pressing strategies", "How to rotate effectively with your wide player to create space", "Explore defending in a back three and a back four ", "How to defend against one striker or two strikers", "How to position to help build play from the back", "How to deal with being pressed from the inside or outside", "How to defend when there is no pressure on the ball", "Recognise where to set the defensive line to play offside", "When to stay wide and when to come inside as a wide midfielder", "How to play as single pivot in midfield or as a double pivot", "How to play in a midfield two, a midfield three or midfield four", "How to position to get on the ball from the defenders", "How to play against a midfield two, a midfield three or midfield four", "When to stay wide and when to come inside as a wide forward", "When to pass and when to dribble", "How to rotate effectively with your full back to create space", "Recognise what type of cross needs to be delivered", "Know when to make movements to come short or when to go in behind", "How to position to anticipate second balls", "How to play as a lone centre forward and how to play as a front two", "When to come short and when to make a penetrating run", "How to high press against a back four or back three", "Movement to create space to support build up play", "Movement to create space inside the penalty box.", "Knows when to play feet or space.", "Recognises what type of pass to play depending on opposition shape", "Takes up suitable positions to defend the cross", "Makes suitable decisions to deal with the cross (catch or punch).", "Knows how and where to set in relation to the shot.", "Recognises when to use different techniques to defend the goal.", "Influences defenders to deny goal scoring opportunties.", "Support positions towards or away from the ball", "How to position to help build play from the back and outplay different pressing strategies", "How to press the game in different ways as a full back in different formations", "When to position on the inside or outside and high or low in the pitch to support the ball", "How to effectively position to lock play down in the opposition half", "How to defend the back post effectively on crosses.", "How to defend when overloaded in wide areas", "How to effectively support your wide player and overload the opposition full back", "How to defend in a mid-block or deep block", "Understand the positional requirements of playing in a back three and a back four.", "How to mark effectively against one strike or two strikers", "How to position to help build play from the back to manipulate the oppositions pressing strategy", "Know how to deal with opposition midfielders playing in the pocket. ", "Know when to play short and when to play long from the back.", "Know how to position effectively when there is no pressure on the ball.", "Organise the defensive line to play offside.", "Know when to run into space or when to support a pass and receive to feet.", "Know when to stay wide and when to come inside as a wide midfielder", "Know how to rotate with full backs and central midfielders to create space", "Know when to come inside or go outside when you have the ball at your feet.", "Know how to lose your opponent with quick and late movements", "Know which cross needs to be delivered depending on your position", "Know when to position on the outside to receive the ball.", "Know the midfield roles of a single pivot, double pivot or number 8 in midfield.", "Know when to hold your position or run forwards as a central midfielder", "Know how to pin an opponent as a central midfielder", "How to defend effectively in midfield (when to press, when to drop, when to cover).", "Know how to defend as a midfield three or four.", "Know how to rotate with other central midfielders to create space to receive.", "Know how to make blind side runs in behind the back line", "Know how to create seperation between you and your opponent when making a run in behind", "Know how to press the game as a striker", "Know how to play in a mid-block or low block and screen midfielders as a striker", "Know how to make double movements in and out the penalty box to create space", "Know when to make runs across your opponent inside the penalty box.", "Know how to pin your defender to receive the ball to feet", "Know how to win free kicks off your opponent", "Attribute3", "Speed", "Mobility", "Agility", "Acceleration", "Power", "Strength", "Attribute4", "Confidence", "Decision Making", "Communication", "Focus", "Leadership", "Resilience"}),
    #"Removed Columns" = Table.RemoveColumns(#"Removed Other Columns",{"Helper"}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"ID", "Forename(s)", "Surname", "Date of Birth", "Age Group", "Position", "Attribute1", "Attribute2", "Dealing with 1v1's", "Distribution techniques (feet or space)", "Stretching play or coming short", "Noticing where there is space and spreading out", "How to position to make the pitch smaller", "How to mark an opponent", "When to come out and effect crosses", "Shot stopping", "Defending the space to prevent 1v1's", "Distribution techniques (playing into or onto).", "Organising markers on corners, walls on free kicks etc", "Positioning to play out from the back", "How to bring an opponent towards you to play round them.", "How to read an opponents body shape to spot triggers", "How to create a 2v1 overload on an opponent", "Where to position to receive", "Defending in balance principles", "Defending out of balance principles", "When to run forward and when to hold your position", "When to combine and when to dribble", "Forward runs to penetrate", "How to press the opposition back line", "Noticing where overloads are to help the team build from the back line.", "Take up suitable start positions to help sweep up long balls played behind the backline", "How to deal with and organise walls and marking positions for defending set pieces", "Know when to ask for more pressure on the ball or when a clearance needs to be made", "Notice how high the opposition are pressing to influence your own distribution.", "Dealing with crosses", "Explore different pressing strategies", "How to rotate effectively with your wide player to create space", "Explore defending in a back three and a back four ", "How to defend against one striker or two strikers", "How to position to help build play from the back", "How to deal with being pressed from the inside or outside", "How to defend when there is no pressure on the ball", "Recognise where to set the defensive line to play offside", "When to stay wide and when to come inside as a wide midfielder", "How to play as single pivot in midfield or as a double pivot", "How to play in a midfield two, a midfield three or midfield four", "How to position to get on the ball from the defenders", "How to play against a midfield two, a midfield three or midfield four", "When to stay wide and when to come inside as a wide forward", "When to pass and when to dribble", "How to rotate effectively with your full back to create space", "Recognise what type of cross needs to be delivered", "Know when to make movements to come short or when to go in behind", "How to position to anticipate second balls", "How to play as a lone centre forward and how to play as a front two", "When to come short and when to make a penetrating run", "How to high press against a back four or back three", "Movement to create space to support build up play", "Movement to create space inside the penalty box.", "Knows when to play feet or space.", "Recognises what type of pass to play depending on opposition shape", "Takes up suitable positions to defend the cross", "Makes suitable decisions to deal with the cross (catch or punch).", "Knows how and where to set in relation to the shot.", "Recognises when to use different techniques to defend the goal.", "Influences defenders to deny goal scoring opportunties.", "Support positions towards or away from the ball", "How to position to help build play from the back and outplay different pressing strategies", "How to press the game in different ways as a full back in different formations", "When to position on the inside or outside and high or low in the pitch to support the ball", "How to effectively position to lock play down in the opposition half", "How to defend the back post effectively on crosses.", "How to defend when overloaded in wide areas", "How to effectively support your wide player and overload the opposition full back", "How to defend in a mid-block or deep block", "Understand the positional requirements of playing in a back three and a back four.", "How to mark effectively against one strike or two strikers", "How to position to help build play from the back to manipulate the oppositions pressing strategy", "Know how to deal with opposition midfielders playing in the pocket. ", "Know when to play short and when to play long from the back.", "Know how to position effectively when there is no pressure on the ball.", "Organise the defensive line to play offside.", "Know when to run into space or when to support a pass and receive to feet.", "Know when to stay wide and when to come inside as a wide midfielder", "Know how to rotate with full backs and central midfielders to create space", "Know when to come inside or go outside when you have the ball at your feet.", "Know how to lose your opponent with quick and late movements", "Know which cross needs to be delivered depending on your position", "Know when to position on the outside to receive the ball.", "Know the midfield roles of a single pivot, double pivot or number 8 in midfield.", "Know when to hold your position or run forwards as a central midfielder", "Know how to pin an opponent as a central midfielder", "How to defend effectively in midfield (when to press, when to drop, when to cover).", "Know how to defend as a midfield three or four.", "Know how to rotate with other central midfielders to create space to receive.", "Know how to make blind side runs in behind the back line", "Know how to create seperation between you and your opponent when making a run in behind", "Know how to press the game as a striker", "Know how to play in a mid-block or low block and screen midfielders as a striker", "Know how to make double movements in and out the penalty box to create space", "Know when to make runs across your opponent inside the penalty box.", "Know how to pin your defender to receive the ball to feet", "Know how to win free kicks off your opponent", "Attribute3", "Speed", "Mobility", "Agility", "Acceleration", "Power", "Strength", "Attribute4", "Confidence", "Decision Making", "Communication", "Focus", "Leadership", "Resilience"}, "Attribute", "Value"),
    #"Removed Columns1" = Table.RemoveColumns(#"Unpivoted Columns",{"Attribute1"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Attribute", "Technical Base Attribute"}, {"Value", "Technical Base Rating"}}),
    #"Unpivoted Columns1" = Table.UnpivotOtherColumns(#"Renamed Columns", {"ID", "Forename(s)", "Surname", "Date of Birth", "Age Group", "Position", "Attribute2", "Attribute3", "Speed", "Mobility", "Agility", "Acceleration", "Power", "Strength", "Attribute4", "Confidence", "Decision Making", "Communication", "Focus", "Leadership", "Resilience", "Technical Base Attribute", "Technical Base Rating"}, "Attribute", "Value"),
    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns1",{{"Attribute", "Tactical Base Attribute"}, {"Value", "Tactical Base Rating"}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns1",{"Attribute2"}),
    #"Unpivoted Columns2" = Table.UnpivotOtherColumns(#"Removed Columns2", {"ID", "Forename(s)", "Surname", "Date of Birth", "Age Group", "Position", "Attribute3", "Attribute4", "Confidence", "Decision Making", "Communication", "Focus", "Leadership", "Resilience", "Technical Base Attribute", "Technical Base Rating", "Tactical Base Attribute", "Tactical Base Rating"}, "Attribute", "Value"),
    #"Renamed Columns2" = Table.RenameColumns(#"Unpivoted Columns2",{{"Attribute", "Athletic Attribute"}, {"Value", "Athletic Base Rating"}, {"Tactical Base Attribute", "Tactical Attribute"}, {"Technical Base Attribute", "Technical Attribute"}}),
    #"Unpivoted Columns3" = Table.UnpivotOtherColumns(#"Renamed Columns2", {"ID", "Forename(s)", "Surname", "Date of Birth", "Age Group", "Position", "Attribute3", "Attribute4", "Technical Attribute", "Technical Base Rating", "Tactical Attribute", "Tactical Base Rating", "Athletic Attribute", "Athletic Base Rating"}, "Attribute", "Value"),
    #"Renamed Columns3" = Table.RenameColumns(#"Unpivoted Columns3",{{"Attribute", "Psychological Attribute"}, {"Value", "Psychological Base Rating"}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns3",{"Attribute3", "Attribute4"})
in
    #"Removed Columns3"
